### ISSUE TITLE
How to retrieve using anyApprovalStatus() by default?

### ISSUE THREAD

**Issue by ghost** [mtvs/eloquent-approval#5]
I'm wondering which is the best way to return records using anyApprovalStatus by default. Maybe a global scope? What you suggest?

I'm already doing it for relationships:

```php
public function documents(): HasMany
{
   return $this->hasMany(Document::class)->anyApprovalStatus();
}
```

**Comment by mtvs** [comment]
Hi Ricardo,

`ApprovalScope::apply()` add the condition that excludes non approved models from query results. So you can Extend the class and override the method with an empty one. Then you need to override `bootApprovable()` to register your custom scope instead of the default one.

```php
<?php

namespace App;

use Mtvs\EloquentApproval\ApprovalScope as BaseScope;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class ApprovalScope extends BaseScope
{
	public function apply(Builder $builder, Model $model)
	{
		// Skipping applying the global scope
	}
}
```
You could override the `bootApprovable()` in your model:

```php
use App\ApprovalScope;
use Mtvs\EloquentApproval\ApprovableObserver;

    public static function bootApprovable() 
    {
        static::addGlobalScope(new ApprovalScope());

        static::observe(ApprovableObserver::class);
    }
```
